version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: falconeye_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: unless-stopped

volumes:
  mongodb_data:
  mongodb_config:
