<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:eb="http://www.ebxml.org/namespaces/messageHeader" xmlns:wsse="http://schemas.xmlsoap.org/ws/2002/12/secext" xmlns:mf="http://www.atse.sabre.com/Availability/ws/Multiflight" name="MultiFlightXmlWSDL" targetNamespace="http://www.atse.sabre.com/Availability/ws/Multiflight">

    <types>
        <xsd:schema targetNamespace="http://webservices.sabre.com/pnrbuilder/getprice">
            <xsd:import namespace="http://schemas.xmlsoap.org/ws/2002/12/secext" schemaLocation="wsse.xsd"/>
            <xsd:import namespace="http://www.ebxml.org/namespaces/messageHeader" schemaLocation="msg-header-2_0.xsd"/>

            <xsd:import namespace="http://www.atse.sabre.com/Availability/ws/Multiflight" schemaLocation="MultiFlightXml.RQ_RS.xsd"/>
        </xsd:schema>
    </types>

    <message name="ASAAInput">
        <part name="header" element="eb:MessageHeader"/>
        <part name="header2" element="wsse:Security"/>
        <part name="body" element="mf:MultiFlightRQ"/>
    </message>

    <message name="ASAAOutput">
        <part name="header" element="eb:MessageHeader"/>
        <part name="header2" element="wsse:Security"/>
        <part name="body" element="mf:MultiFlightRS"/>
    </message>

    <portType name="ASAAPortType">
        <operation name="ASAAOperation">
            <input message="mf:ASAAInput"/>
            <output message="mf:ASAAOutput"/>
        </operation>
    </portType>

    <binding name="ASAASoapBinding" type="mf:ASAAPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ASAAOperation">
            <soap:operation/>
            <input>
                <soap:header message="mf:ASAAInput" part="header" use="literal"/>
                <soap:header message="mf:ASAAInput" part="header2" use="literal"/>
                <soap:body parts="body" use="literal"/>
            </input>
            <output>
                <soap:header message="mf:ASAAOutput" part="header" use="literal"/>
                <soap:header message="mf:ASAAOutput" part="header2" use="literal"/>
                <soap:body parts="body" use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="ASAAService">
        <port name="ASAAPortType" binding="mf:ASAASoapBinding">
            <soap:address location="https://webservices.platform.sabre.com/websvc"/>
        </port>
    </service>

</definitions>
